# Generated by Django 4.1.3 on 2023-02-21 20:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiringLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiring_link_2', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField(auto_now_add=True)),
                ('seconds_to_expiration', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(30000)])),
                ('base_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_upload.image')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_upload.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='ExpiringImageLink',
        ),
    ]
