# Generated by Django 4.1.3 on 2023-02-23 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0002_expiringlink_delete_expiringimagelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiringlink',
            name='base_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='image_upload.image'),
        ),
    ]
