# Generated by Django 4.1.3 on 2023-02-23 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0003_alter_expiringlink_base_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiringlink',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='image_upload.profile'),
        ),
    ]
