# Generated by Django 4.1.3 on 2023-02-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0006_alter_binaryimage_binary_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binaryimage',
            name='binary_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
