# Generated by Django 4.1.3 on 2022-12-31 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('number_of_question', models.AutoField(db_column='Question number', primary_key=True, serialize=False, unique=True)),
                ('question_content', models.TextField(max_length=1000)),
                ('answer_a', models.TextField(max_length=250)),
                ('answer_b', models.TextField(max_length=250)),
                ('answer_c', models.TextField(max_length=250)),
                ('question_notes', models.TextField(max_length=1000)),
                ('a_is_correct', models.BooleanField()),
                ('b_is_correct', models.BooleanField()),
                ('c_is_correct', models.BooleanField()),
            ],
        ),
    ]
