# Generated by Django 4.1.3 on 2023-02-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_question', models.PositiveIntegerField()),
                ('answer_a', models.BooleanField()),
                ('answer_b', models.BooleanField()),
                ('answer_c', models.BooleanField()),
                ('answer_is_proper', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('number_of_question', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('question_content', models.TextField(max_length=1000)),
                ('answer_a', models.TextField(max_length=250)),
                ('answer_b', models.TextField(max_length=250)),
                ('answer_c', models.TextField(max_length=250)),
                ('a_is_correct', models.BooleanField()),
                ('b_is_correct', models.BooleanField()),
                ('c_is_correct', models.BooleanField()),
                ('question_notes', models.TextField(max_length=1000)),
            ],
        ),
    ]
