# Generated by Django 4.1.3 on 2023-02-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_a',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_b',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_c',
            field=models.BooleanField(blank=True),
        ),
    ]
