# Generated by Django 4.1.3 on 2022-12-31 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='number_of_question',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
