# Generated by Django 4.1.3 on 2023-01-30 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_answer_number_of_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
    ]
