# Generated by Django 4.1.3 on 2023-01-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_remove_answer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_is_proper',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
