# Generated by Django 4.1.3 on 2023-02-02 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_answer_answer_is_proper'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
